import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Nav from "./components/Nav";
import Sidebar from "./components/Sidebar";
import Loading from "./components/Loading";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dengue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="light">
        <div>
          <Nav />

          <div className="grid grid-cols-8">
            <div className="col-span-2">
              <Sidebar />
            </div>
            <div className="col-span-6 justify-center ml-10 overflow-auto flex h-screen">
              <Suspense fallback={<Loading />} className="justify-around">
                {children}
              </Suspense>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
